server_url: https://headscale.dev2sec.io.vn

listen_addr: 0.0.0.0:8080

database:
  type: sqlite
  sqlite:
    path: /var/lib/headscale/db.sqlite

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

  # Strategy used for allocation of IPs to nodes, available options:
  # - sequential (default): assigns the next free IP from the previous given
  #   IP. A best-effort approach is used and Headscale might leave holes in the
  #   IP range or fill up existing holes in the IP range.
  # - random: assigns the next free IP from a pseudo-random IP generator (crypto/rand).
  allocation: sequential

private_key_path: /var/lib/headscale/private.key

noise:
  private_key_path: /var/lib/headscale/noise_private.key

log:
  level: info

dns:
  magic_dns: true
  base_domain: tailnet.dev2sec.io.vn
  override_local_dns: true
  nameservers:
    global:
      - 1.1.1.1
      - 8.8.8.8
  extra_records_path: /etc/headscale/dns_records.json

derp:
  server:
    enabled: false
  auto_update_enabled: true
  urls:
    - https://controlplane.tailscale.com/derpmap/default

unix_socket: /var/run/headscale/headscale.sock